### ISSUE TITLE
Two Factor authentication

### ISSUE THREAD

**Issue by manojpamk** [saketkc/usc-vpn-linux-setup#1]
Ever since ITS decided to implement Duo 2FA, I seem to end up in a 'login loop'. Any idea how to work with 2FA?

Thanks!

**Comment by saketkc** [comment]
It seems DUO 2Factor was not enabled for OpenVPN on USC's side. I have been able to use
AnyConnect from Cisco to VPN.

1. Go to https://vpn.usc.edu/+CSCOE+/portal.html
2. Download linux client from the 'AnyConnect' tab
3. Run AnyConnect with vpn.usc.edu
