### ISSUE TITLE
Not working - Keep prompting username and password

### ISSUE THREAD

**Issue by michK** [saketkc/usc-vpn-linux-setup#2]
Hi, thank you very much for sharing, this will be very useful (if I can get it ti work).

When I run the script, I am repeatedly asked to enter my username and password,
which makes it seem like my connection doesn't get authorized.

I have tried with the VPNGRP var set to 1-Wireless, 2-Home and 3-OffCampusOther
but get the same behavior.

I am trying to connect with a WiFi dongle connected to a off-campus home router.

Any ideas?

Thanks again for sharing.
Michael

**Comment by saketkc** [comment]
Hi @michK! Thanks for noticing this. I have not been able to get this working after the recent Duo related change. 

I have however been able to use AnyConnect to work:

1. Go to https://vpn.usc.edu/+CSCOE+/portal.html
2. Download linux client from the 'AnyConnect' tab
3. Run AnyConnect with vpn.usc.edu

Let me know if you face any issues. If I get this to work without AnyConnect, I will update it here.

**Comment by michK** [comment]
Great, that worked for me!

Thanks a lot.
